# Generated by Django 3.2.7 on 2021-09-28 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='product_description',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='listings',
            name='product_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='listings',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='listings',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
